name: 🐛 Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de signaler ce bug. Veuillez fournir autant de détails que possible pour nous aider à reproduire et corriger le problème.

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Une description claire et concise du problème
      placeholder: Décrivez ce qui ne fonctionne pas...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Étapes détaillées pour reproduire le comportement
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Description claire de ce qui devrait se passer
      placeholder: Je m'attendais à...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Description de ce qui se passe actuellement
      placeholder: Au lieu de cela...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environnement
      description: Informations sur votre environnement
      placeholder: |
        - OS: [ex. Ubuntu 20.04]
        - Node.js: [ex. 18.0.0]
        - Version du package: [ex. 1.0.0]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Informations supplémentaires
      description: Tout autre contexte utile (logs, captures d'écran, etc.)
      placeholder: Ajoutez tout contexte supplémentaire ici...
    validations:
      required: false