name: docs

on:
  push:
    branches: [develop, main]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with: 
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: cd docs && npm ci
      - run: npm run docs:build
      - run: touch docs/site/.nojekyll
      
      # Build wizard UI
      - run: cd docs/wizard && npm ci
      - run: cd docs/wizard && npm run build
      - run: mkdir -p docs/wizard-dist
      - run: cp -r docs/wizard/dist/* docs/wizard-dist/
      - run: touch docs/wizard-dist/.nojekyll

      - uses: actions/configure-pages@v4
      
      # Merge both builds
      - run: mkdir -p docs/site/wizard
      - run: cp -r docs/wizard-dist/* docs/site/wizard/
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment